# Generated by Django 3.2.25 on 2025-02-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='imagen',
        ),
    ]
